import { z } from "zod";

export enum DataType {
  FILE = "FILE",
  TEXT = "TEXT",
  CSV = "CSV",
  INT = "INT",
  FLOAT = "FLOAT",
  CODE = "CODE",
  R_CODE = "R_CODE",
  EMBEDDINGS = "EMBEDDINGS",
  JSON = "JSON",
  IMAGE = "IMAGE",
  REPORT = "REPORT",
  TEMPLATE = "TEMPLATE",
  LIST = "LIST",
  AGGREGATED = "AGGREGATED",
  PROPERTY_SELECTOR = "PROPERTY_SELECTOR",
  PROPERTY_GETTER = "PROPERTY_GETTER",
  LIST_INDEX_GETTER = "LIST_INDEX_GETTER",
  WORKFLOW = "WORKFLOW",
  BSGN_GRAPH = "BSGN_GRAPH",
  CYTOSCAPE = "CYTOSCAPE",
  PASSWORD = "PASSWORD",
  BAR_CHART = "BAR_CHART",
  LINE_CHART = "LINE_CHART",
  AUDIO = "AUDIO",
  BOOL = "BOOL",
  STREAM = "STREAM",
  SELECT = "SELECT",
  ANY = "ANY",
  NULL = "NULL",
}

export const agentSchema = z.object({
  instruction: z.string().describe("The main instruction or task description for the workflow."),
  agentName: z.string().describe("The name of the agent responsible for executing the workflow."),
  inputs: z.array(
    z.object({
      name: z.string().describe("The name of the input parameter."),
      dataType: z.nativeEnum(DataType).describe("The data type of the input parameter."),
    })
  ).describe("A list of input parameters required for the workflow."),
  reasoningChain: z.array(
    z.object({
      reasoningType: z.string().describe("The type or method of reasoning used (e.g., 'Search')."),
      reasoningDescription: z.string().describe("A description of what the reasoning step does."),
      executionTime: z.number().describe("Estimated execution time for this reasoning step in seconds."),
      output: z.array(
        z.object({
          type: z.literal("TEXT").describe("The type of output produced by the reasoning step (currently fixed to TEXT)."),
          content: z.string().describe("The actual content or result of the reasoning step."),
        })
      ).describe("List of outputs generated by the reasoning step."),
    })
  ).describe("A chain of reasoning steps used to achieve the workflow goal."),
  timeSavings: z.number().describe("Estimated time saved by using this workflow, in seconds."),
});
