services:
  lunarcore:
    build:
      context: ./lunarcore
      dockerfile: Dockerfile
    network_mode: "host"

  lunarflow:
    build:
      context: ./lunarflow
      dockerfile: Dockerfile
    network_mode: "host"