import uuid
from lunarbase.modeling.data_models import WorkflowModel
import pytest
import os
from pathlib import Path
from lunarbase.domains.workflow.controllers.workflow_controller import WorkflowController
from unittest.mock import MagicMock

@pytest.fixture
def mock_agent_copilot():
    mock = MagicMock()
    # Return a simple WorkflowModel for any call to generate_workflow
    mock.generate_workflow.return_value = WorkflowModel(
        name="Mocked Workflow",
        description="Generated by mock",
        id=str(uuid.uuid4()),
    )
    return mock

@pytest.fixture
def mock_workflow_search_index():
    mock = MagicMock()
    # The index method does nothing, just a stub
    mock.index.return_value = None
    return mock

@pytest.fixture
def controller(lunar_context,mock_agent_copilot,mock_workflow_search_index):
    return WorkflowController(
        config=lunar_context.lunar_config,
        lunar_registry=lunar_context.lunar_registry,
        workflow_repository=lunar_context.workflow_repository,
        agent_copilot=mock_agent_copilot,
        workflow_search_index=mock_workflow_search_index,
        persistence_layer=lunar_context.persistence_layer,
    )

class TestTmpSave:
    def test_returns_temporary_saved_workflow(self, controller, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        workflow = WorkflowModel(
            name="Test Workflow",
            description="A test workflow",
            id=str(uuid.uuid4()),
        )
        saved_workflow = controller.tmp_save(workflow, user_id)
        assert saved_workflow.id == workflow.id
        assert saved_workflow.name == workflow.name
        assert saved_workflow.description == workflow.description
    

    def test_saves_workflow_in_tmp_path(self, controller, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        workflow = WorkflowModel(
            name="Test Workflow",
            description="A test workflow",
            id=str(uuid.uuid4()),
        )
        controller.tmp_save(workflow, user_id)

        path = Path(config.USER_DATA_PATH, user_id, config.TMP_PATH, f"{workflow.id}.json")

        assert path.exists()

class TestTmpDelete:
    def test_deletes_temporary_saved_workflow(self, controller, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        workflow = WorkflowModel(
            name="Test Workflow",
            description="A test workflow",
            id=str(uuid.uuid4()),
        )
        path = Path(config.USER_DATA_PATH, user_id, config.TMP_PATH, f"{workflow.id}.json")
        controller.tmp_save(workflow, user_id)

        assert path.exists()

        assert controller.tmp_delete(workflow.id, user_id)

        assert not path.exists()

class TestSave:
    def test_saves_workflow(self, controller, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        workflow = WorkflowModel(
            name="Test Workflow",
            description="A test workflow",
            id=str(uuid.uuid4()),  
        )
        saved_workflow = controller.save(workflow, user_id)
        assert saved_workflow.id == workflow.id
        assert saved_workflow.name == workflow.name
        assert saved_workflow.description == workflow.description

    def test_saves_default_workflow_if_none_provided(self, controller, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        saved_workflow = controller.save(None, user_id)
        assert saved_workflow.id is not None
        assert saved_workflow.name == "Untitled"
        assert saved_workflow.description == ""

    def test_initializes_workflow_dirs(self, controller, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        workflow = WorkflowModel(
            name="Test Workflow",
            description="A test workflow",
            id=str(uuid.uuid4()),  
        )
        controller.save(workflow, user_id)

        workflow_root_path = Path(
            config.USER_DATA_PATH,
            user_id,
            config.USER_WORKFLOW_ROOT,
            workflow.id,
        )
        workflow_venv_path = Path(
            workflow_root_path,
            config.USER_WORKFLOW_VENV_ROOT,
        )
        workflow_files_path = Path(
            workflow_root_path,
            config.FILES_PATH,
        )
        workflow_reports_path = Path(
            workflow_root_path,
            config.REPORT_PATH,
        )
        assert workflow_root_path.exists()
        assert workflow_venv_path.exists()
        assert workflow_files_path.exists()
        assert workflow_reports_path.exists()


class TestAutoCreate:
    def test_auto_create_uses_agent_copilot(self, controller, mock_agent_copilot, config):
        user_id = config.DEFAULT_USER_TEST_PROFILE
        intent = "Create a workflow for data processing"
        workflow = controller.auto_create(intent, user_id)

        mock_agent_copilot.generate_workflow.assert_called_once_with(intent)

        assert workflow.name == mock_agent_copilot.generate_workflow.return_value.name
        assert workflow.description == mock_agent_copilot.generate_workflow.return_value.description
        assert workflow.id == mock_agent_copilot.generate_workflow.return_value.id